INSERT INTO employee (first_Name, last_Name, salary) VALUES ('Daisy', 'Dukes', 300000)
INSERT INTO employee (first_Name, last_Name, salary) VALUES ('Mickey', 'Mouse', 30000)
INSERT INTO employee (first_Name, last_Name, salary) VALUES ('Donald', 'Duck', 400000)
INSERT INTO employee (first_Name, last_Name, salary) VALUES ('John', 'Snow', 600000)
INSERT INTO employee (first_Name, last_Name, salary) VALUES ('Ronald', 'Reagan', 500000)
INSERT INTO employee (first_Name, last_Name, salary) VALUES ('Mike', 'Johnson', 200000)
INSERT INTO department (department_Name) VALUES ('Marketing')
INSERT INTO department (department_Name) VALUES ('Finance')
INSERT INTO department (department_Name) VALUES ('Software Engineers')
INSERT INTO department (department_Name) VALUES ('Cyber Security')
INSERT INTO department (department_Name) VALUES ('Operations Management')
